#!/bin/bash
###############################################################################
# update_dns.sh
# 
# Generates Unbound local zone configuration from TSV source files.
# Creates backups before modification and validates configs before restart.
#
# Usage: sudo /usr/local/sbin/update_dns.sh
###############################################################################

set -euo pipefail

# Configuration
TSV_FILE="/etc/unbound/hosts.d/mykk.foo.tsv"
CONF_FILE="/etc/unbound/unbound.conf.d/local-zone-mykk-foo.conf"
BACKUP_DIR="/etc/unbound/backups"
DOMAIN="mykk.foo"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}ERROR: This script must be run as root${NC}" 
   exit 1
fi

# Check if TSV file exists
if [[ ! -f "$TSV_FILE" ]]; then
    echo -e "${RED}ERROR: TSV file not found: $TSV_FILE${NC}"
    exit 1
fi

# Create backup directory
mkdir -p "$BACKUP_DIR"

# Create backup of existing config
if [[ -f "$CONF_FILE" ]]; then
    BACKUP_FILE="$BACKUP_DIR/local-zone-mykk-foo.conf.$(date +%Y%m%d-%H%M%S).bak"
    cp "$CONF_FILE" "$BACKUP_FILE"
    echo -e "${GREEN}✓${NC} Backup created: $BACKUP_FILE"
fi

# Generate new configuration
echo -e "${YELLOW}Generating new configuration...${NC}"

{
    echo "# Generated by update_dns.sh on $(date)"
    echo "# Source: $TSV_FILE"
    echo ""
    echo "server:"
    echo "    local-zone: \"${DOMAIN}.\" static"
    echo ""
    echo "    # A records"
    
    while IFS=$'\t' read -r hostname ip aliases; do
        # Skip comments and empty lines
        [[ "$hostname" =~ ^#.*$ ]] && continue
        [[ -z "$hostname" ]] && continue
        
        echo "    local-data: \"${hostname}.${DOMAIN}. IN A ${ip}\""
    done < "$TSV_FILE"
    
    echo ""
    echo "    # PTR records (reverse DNS)"
    
    while IFS=$'\t' read -r hostname ip aliases; do
        [[ "$hostname" =~ ^#.*$ ]] && continue
        [[ -z "$hostname" ]] && continue
        
        echo "    local-data-ptr: \"${ip} ${hostname}.${DOMAIN}.\""
    done < "$TSV_FILE"
    
    echo ""
    echo "    # CNAME aliases"
    
    while IFS=$'\t' read -r hostname ip aliases; do
        [[ "$hostname" =~ ^#.*$ ]] && continue
        [[ -z "$hostname" ]] && continue
        [[ -z "$aliases" ]] && continue
        
        # Split comma-separated aliases
        IFS=',' read -ra ALIAS_ARRAY <<< "$aliases"
        for alias in "${ALIAS_ARRAY[@]}"; do
            alias=$(echo "$alias" | xargs)  # Trim whitespace
            [[ -z "$alias" ]] && continue
            echo "    local-data: \"${alias}.${DOMAIN}. IN CNAME ${hostname}.${DOMAIN}.\""
        done
    done < "$TSV_FILE"
    
    echo ""
    echo "    # External CNAMEs (if needed)"
    echo "    # local-data: \"www.${DOMAIN}. IN CNAME mykk.us.\""
    
} > "$CONF_FILE"

echo -e "${GREEN}✓${NC} Configuration file generated: $CONF_FILE"

# Validate configuration
echo -e "${YELLOW}Validating configuration...${NC}"
if unbound-checkconf > /dev/null 2>&1; then
    echo -e "${GREEN}✓${NC} Configuration is valid"
else
    echo -e "${RED}✗ ERROR: Configuration validation failed!${NC}"
    echo ""
    echo "Unbound configuration errors:"
    unbound-checkconf
    echo ""
    echo -e "${YELLOW}Restoring from backup...${NC}"
    
    if [[ -f "$BACKUP_FILE" ]]; then
        cp "$BACKUP_FILE" "$CONF_FILE"
        echo -e "${GREEN}✓${NC} Restored previous configuration"
    fi
    
    exit 1
fi

# Restart Unbound
echo -e "${YELLOW}Restarting Unbound...${NC}"
if systemctl restart unbound; then
    echo -e "${GREEN}✓${NC} Unbound restarted successfully"
else
    echo -e "${RED}✗ ERROR: Failed to restart Unbound${NC}"
    exit 1
fi

# Verify Unbound is running
sleep 1
if systemctl is-active --quiet unbound; then
    echo -e "${GREEN}✓${NC} Unbound is running"
else
    echo -e "${RED}✗ WARNING: Unbound is not running${NC}"
    exit 1
fi

echo ""
echo -e "${GREEN}✓✓✓ DNS configuration updated successfully! ✓✓✓${NC}"
echo ""
echo "Summary:"
echo "  - Source: $TSV_FILE"
echo "  - Config: $CONF_FILE"
echo "  - Backup: $BACKUP_FILE"
echo ""
echo "Test with: dig @localhost example.${DOMAIN}"
